# Generated by Django 4.2.6 on 2023-10-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0004_category_remove_business_business_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("website", models.CharField(max_length=100)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="campaign", to="businesses.business"
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
        migrations.CreateModel(
            name="CampaignHeadlines",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=90)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="headlines", to="campaigns.campaign"
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Headline",
                "verbose_name_plural": "Campaign Headlines",
            },
        ),
        migrations.CreateModel(
            name="CampaignDescriptions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=90)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Description",
                "verbose_name_plural": "Campaigns Descriptions",
            },
        ),
    ]
