# Generated by Django 4.2.6 on 2023-10-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0006_alter_business_user"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="campaigns", to="businesses.business"
            ),
        ),
    ]
