# Generated by Django 4.2.6 on 2023-10-20 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_alter_campaign_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="cell_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="country",
            field=models.CharField(default="Uzbekistan", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="language",
            field=models.CharField(
                choices=[
                    ("google", "google"),
                    ("microsoft", "microsoft"),
                    ("facebook", "facebook"),
                    ("instagram", "instagram"),
                    ("twitter", "twitter"),
                    ("banner", "banner"),
                ],
                default="Uzbek",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="platform",
            field=models.CharField(default="google", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="purpose",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="status",
            field=models.IntegerField(
                choices=[(0, "DRAFT"), (1, "ACTIVE"), (2, "DISABLED")], default=0, editable=False
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="website_page_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
