# Generated by Django 4.2.6 on 2023-10-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_campaign_cell_phone_campaign_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="language",
            field=models.CharField(
                choices=[("english", "english"), ("russian", "russian"), ("other", "other")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="platform",
            field=models.CharField(
                choices=[
                    ("google", "google"),
                    ("microsoft", "microsoft"),
                    ("facebook", "facebook"),
                    ("instagram", "instagram"),
                    ("twitter", "twitter"),
                    ("banner", "banner"),
                ],
                max_length=10,
            ),
        ),
    ]
