# Generated by Django 4.2.6 on 2023-10-16 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=255)),
                ("business_size", models.CharField(max_length=100)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.CreateModel(
            name="Sites",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=255, verbose_name="URL")),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="businesses.business")),
            ],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
            },
        ),
    ]
