# Generated by Django 4.2.6 on 2023-10-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0002_remove_business_url_alter_business_business_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sites",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="websites", to="businesses.business"
            ),
        ),
    ]
