# Generated by Django 4.2.6 on 2023-10-21 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("businesses", "0006_alter_business_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="business", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
