# Generated by Django 4.2.6 on 2023-10-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="invoice_id",
            field=models.CharField(db_index=True, editable=False, max_length=50),
        ),
    ]
