# Generated by Django 4.2.6 on 2023-10-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[(0, "CREATED"), (1, "PAID"), (2, "EXPIRED"), (3, "PARTPAID")], default=0, editable=False
            ),
        ),
    ]
